# Generated by Django 5.2.18 on 2026-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateDimension',
            fields=[
                ('date_key', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('year', models.PositiveSmallIntegerField(db_column='annee')),
                ('quarter', models.PositiveSmallIntegerField(db_column='trimestre')),
                ('year_quarter', models.CharField(db_column='annee_trimestre', max_length=7)),
                ('month', models.PositiveSmallIntegerField(db_column='mois')),
                ('year_month', models.CharField(db_column='annee_mois', max_length=7)),
                ('month_name', models.CharField(db_column='nom_mois', max_length=10)),
                ('iso_week', models.PositiveSmallIntegerField(db_column='semaine_iso')),
                ('weekday', models.PositiveSmallIntegerField(db_column='jour_semaine')),
            ],
            options={
                'db_table': 'dim_date',
                'ordering': ['date_key'],
            },
        ),
        migrations.CreateModel(
            name='LocationDimension',
            fields=[
                ('location_key', models.AutoField(db_column='localite_key', primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dim_localite',
                'constraints': [models.UniqueConstraint(fields=('country', 'region', 'state', 'city', 'postal_code'), name='unique_delivery_location')],
            },
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('product_key', models.AutoField(db_column='produit_key', primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_produit',
                'constraints': [models.UniqueConstraint(fields=('product_id', 'product_name'), name='unique_product_id_name')],
            },
        ),
    ]
